driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata

platforms:
  - name: centos-7
    driver_config:
      image: "geoffwilliams/puppet:2016.1.2-0"
      platform: rhel
      build_context: true
      provision_command:
        - ln -sf /opt/puppetlabs/puppet/bin/puppet /usr/bin/puppet
        - ln -sf /opt/puppetlabs/puppet/bin/facter /usr/bin/facter
        - ln -sf /opt/puppetlabs/puppet/bin/hiera /usr/bin/hiera       
 
suites:
  - name: first_run
    provisioner:
      manifest: ../modules/only_before_sync/examples/only_before_sync.pp
  - name: second_run
    provisioner:
      puppet_apply_command: |
        export MANIFESTDIR='/tmp/kitchen/manifests'; 
        sudo -E puppet apply /tmp/kitchen/manifests/../modules/only_before_sync/examples/only_before_sync.pp --modulepath=/tmp/kitchen/modules --fileserverconfig=/tmp/kitchen/fileserver.conf 
        sudo -E puppet apply /tmp/kitchen/manifests/../modules/only_before_sync/examples/only_before_sync_second_run.pp --modulepath=/tmp/kitchen/modules --fileserverconfig=/tmp/kitchen/fileserver.conf 

#      custom_install_command: puppet apply /tmp/kitchen/modules/only_before_sync/examples/only_before_sync.pp

#      manifest: ../modules/only_before_sync/examples/only_before_sync_second_run.pp
